### ISSUE TITLE
GitLab image compatability

### ISSUE THREAD

**Issue by dudeisbrendan03** [snyk/snyk-images#50]
Maybe on oversight on my part and I've missed out something, I will upload my Ci/Cd file showing my usage of snyk later today.

It appears the GitLab runner can't run custom images properly, failing to run `exec` on the entry point, however `eval` works 

![image](https://user-images.githubusercontent.com/6009600/206724364-2a4f75e4-b6aa-44cb-aa4e-9b114f597f75.png)

https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1253

I'm not in a position to run my own image on the pipeline at the moment so can't really test it, but I was wondering if I had made a configuration mistake, and if not is it possible to change exec -> eval [here](https://github.com/snyk/snyk-images/blob/347f205c908f6ad7c07cd90137eff4d19602b597/docker-entrypoint.sh#L95) without repercussions to other platforms where this is already functional, like GitHub Actions, CircleCI, etc.

**Comment by dudeisbrendan03** [comment]
```yaml
variables:
  SNYK_TOKEN: $SNYK_TOKEN

# See https://maven.apache.org/docs/3.8.1/release-notes.html#how-to-fix-when-i-get-a-http-repository-blocked for more.
image: maven:3-openjdk-17
stages:
  - compile
  - package
  - verify
  - release
  - test

cache:
  paths:
    - .m2/repository
    - ./target/

snyk:
  image: snyk/snyk:maven-3-openjdk-17
  stage: test
  script:
    - 'snyk monitor --project-name=XXX'
    - 'snyk test'
    - 'snyk test --json > snyk_results.json'
  artifacts:
    when: always
    paths: 
      - snyk_results.json
```

**Comment by PatrickSpies** [comment]
Overriding the entrypoint should fix this:
```yaml
snyk:
  image: 
    name: snyk/snyk:maven-3-openjdk-17
    entrypoint: [""]
...
```
